### ISSUE TITLE
info on loading screen doesn't properly handle $G to reset colors

### ISSUE THREAD

**Issue by ezio416** [MisfitMaid/tm-map-info#13]
If there's a `$G` in the name of a map to reset colors, this plugin seems to ignore that and keeps applying colors to the rest of the map name.

Loading screen:
<img width="327" alt="Screenshot 2023-10-20 184033" src="https://github.com/MisfitMaid/tm-map-info/assets/37951898/1efdc095-cef0-4717-8820-bb8fec598044">

Trackmania.io:
<img width="137" alt="Screenshot 2023-10-20 184148" src="https://github.com/MisfitMaid/tm-map-info/assets/37951898/82f1ffd2-b4d4-4167-b24a-7bf6ed4ba07d">

**Comment by XertroV** [comment]
i added a thing to treat $g like $z. not sure if that's actually correct or not. btw a tmxid or something would have been useful to quickly test (i didn't test, just started treating g like z)

**Comment by ezio416** [comment]
Yeah sorry I could have provided that. Seems to be working fine now, thank you
