### ISSUE TITLE
add toggle for champion medal

### ISSUE THREAD

**Issue by ezio416** [MisfitMaid/tm-map-info#28]
I want to use the Champion Medals plugin, mainly only to occasionally check them and to build support into my own plugins, but I don't want to see them in Map Info. I had started on a PR for this a while back but it seems to be a lot more complicated than I originally thought...

**Comment by XertroV** [comment]
removing and adding medal times sounds like a pain, but i added a setting to ignore CM medals. it's checked when the map is loaded.
