### ISSUE TITLE
Dedicated integrated medals area

### ISSUE THREAD

**Issue by st-AR-gazer** [MisfitMaid/tm-map-info#7]
Heyo, here is the same suggestion talked about here, MisfitMaid suggested I make a Git Issue, so here we are :)

Discord Post:
``` 
I brought this up with MisfitMaid, but here is a suggestion :).
Add an integrated 'medals area' where the different medals are shown.
Here is what I think would look nice, and what I shared with MisfitMaid:
```
![image](https://github.com/MisfitMaid/tm-map-info/assets/132480072/d1b52ce2-9278-4124-a0e0-7e8931ffea0a)

**Comment by XertroV** [comment]
I added this. It supports champion medals too.

![image](https://github.com/MisfitMaid/tm-map-info/assets/1046448/5d37c8af-b0fa-4cf3-8586-56f123b6c0f4)

**Comment by st-AR-gazer** [comment]
Very nice :)
